"""init

Revision ID: 4cf92fdd79c2
Revises: 
Create Date: 2022-10-22 14:42:45.302232

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4cf92fdd79c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'nodes', ['name', 'key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nodes', type_='unique')
    # ### end Alembic commands ###
